name: Test
description: Test
inputs:
  a:
    description: The directory that contains K8s Manifests
    required: true
    default: ./k8s
  b:
    description: Image Tag
    required: false
runs:
  using: composite
  steps:
    - name: Configure GitHub SSH
      run: |
        echo '${{ inputs.a }}' 
        echo '${{ inputs.b }}'
        echo ${{ inputs.a }}
        echo ${{ inputs.b }}
      shell: bash
